spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5436/hydro
    username: hydro
    password: hydro

  jpa:
    hibernate:
      ddl-auto: update