<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.4.4</version>
        <relativePath/>
    </parent>

    <groupId>hr.fer.hydro</groupId>
    <artifactId>hydro-parent</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>hydro</name>
    <description>
        Sustav za prikupljanje, pohranu, analizu i prikaz hidroloških podataka u računalnom oblaku
    </description>

    <modules>
        <module>api</module>
        <module>service</module>
    </modules>

    <properties>
        <java.version>21</java.version>

        <dependency.lombok.version>1.18.30</dependency.lombok.version>
        <dependency.mapstruct.version>1.5.5.Final</dependency.mapstruct.version>
        <dependency.lombok-mapstruct-binding.version>0.2.0</dependency.lombok-mapstruct-binding.version>

        <dependency.jjwt.version>0.11.5</dependency.jjwt.version>
        <dependency.swagger.version>2.1.0</dependency.swagger.version>
        <dependency.google-zxing.version>3.5.4</dependency.google-zxing.version>
        <dependency.google-auth.version>1.5.0</dependency.google-auth.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>hr.fer.hydro</groupId>
                <artifactId>hydro-api</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>

        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>${dependency.swagger.version}</version>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${dependency.lombok.version}</version>
            <optional>true</optional>
        </dependency>
        
    </dependencies>

    <build>
        <plugins>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.11.0</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>

                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${dependency.lombok.version}</version>
                        </path>

                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>${dependency.mapstruct.version}</version>
                        </path>

                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok-mapstruct-binding</artifactId>
                            <version>${dependency.lombok-mapstruct-binding.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>

        </plugins>
    </build>

</project>
