server:
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
  port: 8081
  error:
    include-stacktrace: never

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: hydro
    password: hydro
    url: jdbc:postgresql://localhost:5436/hydro
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

